<a href="https://colab.research.google.com/github/DevCodeByte/LearnML/blob/main/ML_Day3%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("day-3")

day-3


In [ ]:
t1 = (10,20,"ntt",2.5)
print(t1)

(10, 20, 'ntt', 2.5)


In [ ]:
print(type(t1))

<class 'tuple'>


In [ ]:
# Constructor tuple
t2 = tuple((10,20,"ntt",2.5))
print(t2)

(10, 20, 'ntt', 2.5)


In [ ]:
# Constructor tuple - passing list (check internal braces)
t3 = tuple([10,20,"ntt",2.5])
print(t3)
print(type(t3))

(10, 20, 'ntt', 2.5)
<class 'tuple'>


In [ ]:
t4 = tuple("deepak")
print(t4)
#but it thows an error with integer, because the int value is not itertable
# t5 = tuple(10)
# print(t5)

# but you can create tuple with one element with a comma
t6 = tuple((10,))
print(t6)


('d', 'e', 'e', 'p', 'a', 'k')
(10,)


In [ ]:
t7 = tuple((25,35,45,55))
print(t7[1])
print(t7[-2])
print(t7[1:3])
print(t7[1:])
print(t7[:3])

35
45
(35, 45)
(35, 45, 55)
(25, 35, 45)


In [ ]:
t7 = tuple((25,35,45,55))
if 35 in t7:
    print("yes")
else:
    print("no")

yes


In [ ]:
#update a tuple
t8 = (20,30,50)
# A item can't be updated in a tuple so argument below is incorrect
# t8[1] = 40

# so we need create convert tuple to list and list to tuple
lt8 = list(t8)
lt8[1] = 40
t8 = tuple(lt8)
print(t8)

(20, 40, 50)


In [ ]:
#delete a tuple
t9 = (20,30,50)
del t9
print(t9)

NameError: name 't9' is not defined

In [ ]:
# iterate
t10 = (20,30,50)
for x in t10:
    print(x)

20
30
50


In [ ]:
# set
d1 = {10, "ntt",30}
print(d1)
print(type(d1))

{10, 'ntt', 30}
<class 'set'>


In [ ]:
# dictionary with index
d2 = {10:"deepak", 20:"sumit",30:"varun"}
print(d2)
print(d2[20])
print(type(d2))

{10: 'deepak', 20: 'sumit', 30: 'varun'}
sumit
<class 'dict'>


In [ ]:
# dictionary of lists
d3 = {10:["deepak","sumit"], 20:"sumit",30:"varun"}
print(d3)
print(d3[10])
print(type(d3));

{10: ['deepak', 'sumit'], 20: 'sumit', 30: 'varun'}
['deepak', 'sumit']
<class 'dict'>


In [ ]:
# creating dictionary using constructor
d4 = dict({10:"deepak", 20:"sumit",30:"varun"})
print(d4)
print(type(d4))

d5 = dict([(10,"deepak"), (20,"sumit"),(30,"varun")])
print(d5)
print(type(d5))

d6 = dict([[10,"deepak"], [20,"sumit"],[30,"varun"]])
print(d6)
print(type(d6))

d7 = dict(((10,"deepak"), (20,"sumit"),(30,"varun")))
print(d7)
print(type(d7))

d8 = dict({"name":"deepak", "age":25, "country":"India"});
print(d8)

{10: 'deepak', 20: 'sumit', 30: 'varun'}
<class 'dict'>
{10: 'deepak', 20: 'sumit', 30: 'varun'}
<class 'dict'>
{10: 'deepak', 20: 'sumit', 30: 'varun'}
<class 'dict'>
{10: 'deepak', 20: 'sumit', 30: 'varun'}
<class 'dict'>
{'name': 'deepak', 'age': 25, 'country': 'India'}


In [ ]:
# Updating dictionary
d9 = {"name":"deepak", "age":25 ,"country":"India"}
d9["age"] = 26
print(d9)
d9.update({"age":27})
print(d9)
d9["salary"] = 20000
print(d9)

{'name': 'deepak', 'age': 26, 'country': 'India'}
{'name': 'deepak', 'age': 27, 'country': 'India'}
{'name': 'deepak', 'age': 27, 'country': 'India', 'salary': 20000}


In [ ]:
#pop item
d10 = {"name":"deepak", "age":25 ,"country":"India"}
d10.pop("age")
print(d10)
d10.popitem()
print(d10)

{'name': 'deepak', 'country': 'India'}
{'name': 'deepak'}


In [ ]:
#finding keys and values of a dictionary
d11 = {"name":"deepak", "age":25 ,"country":"India"}
print(d11.keys())
print(d11.values())


dict_keys(['name', 'age', 'country'])
dict_values(['deepak', 25, 'India'])


In [ ]:
#iterate a dictionary
d12 = {"name":"deepak", "age":25 ,"country":"India"}
for x in d12:
    print(x)
print("---------------")
for x in d12:
    print(d12[x])

name
age
country
---------------
deepak
25
India


In [ ]:
# delete a dictionary
d13 = {"name":"deepak", "age":25 ,"country":"India"}
del d13["age"]
print(d13)

del d13
print(d13)

{'name': 'deepak', 'country': 'India'}


NameError: name 'd13' is not defined

In [ ]:
#import numpy package
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.size)
print(arr.shape)
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
5
(5,)
int64


In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(type(arr2))
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
6
(2, 3)
int64


In [ ]:
# working with 3 dim array
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
print(type(arr3))
print(arr3.ndim)
print(arr3.size)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3
12
(2, 2, 3)


In [1]:
#different numpy arrays
import numpy as np

arr1 = np.array(100)
arr2= np.array([1,2,3,4,5])
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

arr5 = np.array([1,2,3,4,5], ndmin=5)
print(arr5)
print('number of dimensions :', arr5.ndim)


[[[[[1 2 3 4 5]]]]]
number of dimensions : 5


In [3]:
arr2 = np.array([1,2,3,4,5])
print(arr2[::-1])

[5 4 3 2 1]


In [4]:
#checking elment of a two dim array
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3[1,2])

6


In [5]:
#check element of a three dim array
arr4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr4[1,1,2])

6


In [6]:
#check element with negetive indexing
arr5 = np.array([[1,2,3],[4,5,6]])
print(arr5[-1,-2])

5


In [11]:
#slicing of a tuple
arr55 = np.array((1,2,3,4,5))
t = arr5[1:4]
print(t)
print(type(t))
t1 = tuple(t)
print(t1)
print(type(t1))

[[4 5 6]]
<class 'numpy.ndarray'>
(array([4, 5, 6]),)
<class 'tuple'>
[7 8 9]
