<a href="https://colab.research.google.com/github/DevCodeByte/LearnML/blob/main/ML_Day_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#understanding machine learning
#Linear Regression
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

temp = [20, 25, 30, 35, 40]
sale = [13, 21, 25, 35, 38]

#converting one dimensional array to two dimentional as its needed for linear regression
# so here it will convert the 1x5 array (one row, multiple columns) into 5x1 (multiple row, one column) array
x = np.array([temp]).T
# same as x = np.transpose(x)

print(x)
print(x.shape)

y = np.array(sale)
print(y)
print(y.shape)




[[20]
 [25]
 [30]
 [35]
 [40]]
(5, 1)
[13 21 25 35 38]
(5,)


In [9]:
# creating linear regression model
model = LinearRegression()
model.fit(x,y)

y_pred = model.predict(x)
print(y_pred)

[13.6 20.  26.4 32.8 39.2]


In [10]:
#find slope and intercept
print(model.coef_)
print(model.intercept_)

[1.28]
-12.000000000000007


In [11]:
#predicting new value
new_temp = 33
new_sale = model.predict([[new_temp]]) # giving two dimensional array as input
print(new_sale)

[30.24]
