<a href="https://colab.research.google.com/github/DevCodeByte/LearnML/blob/main/panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr1 = np.array(100)
arr2= np.array([1,2,3,4,5])
arr3 = np.array([[1,2,"NTT"],[4,5,6]])
arr4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
1
2
3


In [ ]:
arr5 = np.array([1,2,3,4,5], ndmin=6)
print(arr5)
print('number of dimensions :', arr5.ndim)

[[[[[[1 2 3 4 5]]]]]]
number of dimensions : 6


In [ ]:
arr2= np.array([1,2,3,4,5])
print(arr2[::-1])

[5 4 3 2 1]


In [ ]:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3[-1,-1])

6


In [ ]:
arr4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr4[0,1,2])

6


In [ ]:
arr2= np.array([1,2,3,4,5])
l=arr2[1:4]
print(l)
l2= list(l)
print(type(l2))
print(type(l))

[2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
arr2= np.array([1,2,3,4,5])
print([arr2[-3:-1]])

[array([3, 4])]


In [ ]:
arr3 = np.array([[1,2,3,8,9,10],[4,5,6,9,9,9]])
print(arr3[1:4,1:3])

[[5 6]]


In [ ]:
arr2= np.array([1,2,3,4,1.1])
print(arr2.dtype)
print(arr2[0]+arr2[1])

float64
3.0


In [ ]:
arr2= np.array([1,2,3,4,"NTT"])
print(arr2.dtype)
print(arr2[0]+arr2[1])

<U21
12


In [ ]:
a="ntt"
b="blr"
print(a+b)

nttblr


In [ ]:
arr2= np.array([1.1,2.0,3.0,4.0,5])
print(arr2.dtype)


float64


In [ ]:
arr = np.array([1,2,3,4],dtype="S")
print(arr)
print(arr[0]+arr[1])
print(arr.dtype)

[b'1' b'2' b'3' b'4']
b'12'
|S1


In [ ]:
arr = np.array([1,2,3,4],dtype="i8")
print(arr)
print(arr[0]+arr[1])
print(arr.dtype)

[1 2 3 4]
3
int64


In [ ]:
arr2= np.array([1.1,0,3.0,4.0,0])
na = arr2.astype(bool)
print(na)
print(na.dtype)
print(arr2.dtype)

[ True False  True  True False]
bool
float64


In [ ]:
#copy Vs View

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#Numpy Array Shape

arr3 = np.array([[1,2,3,8,9,10],[4,5,6,9,9,9]])
print(arr3.shape)


(2, 6)


In [ ]:
arr = np.array([[[1,2,3,4],[8,9,10,11]],[[1,2,3,4],[8,9,10,11]]],ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[ 1  2  3  4]
    [ 8  9 10 11]]

   [[ 1  2  3  4]
    [ 8  9 10 11]]]]]
shape of array : (1, 1, 2, 2, 4)


In [ ]:
#reshaping

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,12])
newarr = arr.reshape(2,3,2)
print(newarr)


ValueError: cannot reshape array of size 13 into shape (2,3,2)

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
na = arr.reshape(2,3,-1)
print(na)
print(na.shape)

ValueError: cannot reshape array of size 9 into shape (2,3,newaxis)

In [ ]:
#print(na)
nna = na.reshape(-1)
print(nna)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#Starting with pandas
import pandas as pd
l = [10,20,30,40,50]
df = pd.DataFrame(l)
print(df)

    0
0  10
1  20
2  30
3  40
4  50


In [ ]:
#lets start with dictionary
data = {'Name':['Tom', 'nick', 'krish', 'jack'], 'Age':[20, 21, 19, 18]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18


In [ ]:
#two dimensional array
l = [[1,2,3],[4,5,6]]
df = pd.DataFrame(l)
print(df)

   0  1  2
0  1  2  3
1  4  5  6


In [ ]:
#three dimensional array
l = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
df = pd.DataFrame(l)
print(df)
#by specifying index and columns
df = pd.DataFrame(l,index=['a','b'],columns=['x','y'])
print(df)


           0          1
0  [1, 2, 3]  [4, 5, 6]
1  [1, 2, 3]  [4, 5, 6]
           x          y
a  [1, 2, 3]  [4, 5, 6]
b  [1, 2, 3]  [4, 5, 6]


In [ ]:
from numpy.random import randn
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
print(df)
df = pd.DataFrame(randn(5,4),index=['A', 'B', 'C', 'D', 'E'],columns=['W', 'X', 'Y', 'Z'])
print(df)

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478
          W         X         Y         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
C -1.005187 -0.741790  0.187125 -0.732845
D -1.382920  1.482495  0.961458 -2.141212
E  0.992573  1.192241 -1.046780  1.292765


In [ ]:
#fetch a single column
df['X']

X         Z
A  2.084019  0.230336
B  1.035125  1.939932
C -0.741790 -0.732845
D  1.482495 -2.141212
E  1.192241  1.292765

In [ ]:
#fetch multiple column
df[['W','Z']]

W         Z
A  0.386030  0.230336
B  0.681209  1.939932
C -1.005187 -0.732845
D -1.382920 -2.141212
E  0.992573  1.292765

In [ ]:
#adding a new column
df['N'] = df['W'] + df['Y']
print(df)


          W         X         Y         Z         N
A  0.386030  2.084019 -0.376519  0.230336  0.009512
B  0.681209  1.035125 -0.031160  1.939932  0.650049
C -1.005187 -0.741790  0.187125 -0.732845 -0.818062
D -1.382920  1.482495  0.961458 -2.141212 -0.421462
E  0.992573  1.192241 -1.046780  1.292765 -0.054206


In [ ]:
#delete a column from a view
view = df.drop('N',axis=1); # axis = 0 is row, while axis=1 is column
print(view)
print(df)

          W         X         Y         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
C -1.005187 -0.741790  0.187125 -0.732845
D -1.382920  1.482495  0.961458 -2.141212
E  0.992573  1.192241 -1.046780  1.292765
          W         X         Y         Z         N
A  0.386030  2.084019 -0.376519  0.230336  0.009512
B  0.681209  1.035125 -0.031160  1.939932  0.650049
C -1.005187 -0.741790  0.187125 -0.732845 -0.818062
D -1.382920  1.482495  0.961458 -2.141212 -0.421462
E  0.992573  1.192241 -1.046780  1.292765 -0.054206


In [ ]:
#delete permanently
df.drop('N',axis=1,inplace=True) #inplace=True, it will delete the column from actual array
print(df)

          W         X         Y         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
C -1.005187 -0.741790  0.187125 -0.732845
D -1.382920  1.482495  0.961458 -2.141212
E  0.992573  1.192241 -1.046780  1.292765


In [ ]:
#locating a row
df.loc['A']
df.iloc[2] #iloc works on row indexing starting from 0, so for third row, index = 2

W   -1.005187
X   -0.741790
Y    0.187125
Z   -0.732845
Name: C, dtype: float64

In [ ]:
#locate an element
df.loc['C','Y']

0.1871245217641948

In [ ]:
#locate multiple elements
df.loc[['B','D'],['X','Y']]

X         Y
B  1.035125 -0.031160
D  1.482495  0.961458

In [ ]:
df>0

W      X      Y      Z
A   True   True  False   True
B   True   True  False   True
C  False  False   True  False
D  False   True   True  False
E   True   True  False   True

In [ ]:
df[df>0]

W         X         Y         Z
A  0.386030  2.084019       NaN  0.230336
B  0.681209  1.035125       NaN  1.939932
C       NaN       NaN  0.187125       NaN
D       NaN  1.482495  0.961458       NaN
E  0.992573  1.192241       NaN  1.292765

In [ ]:
#removing rows where value is NaN in column W
dd = df[df['W']>0]
print(dd)

          W         X         Y         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
E  0.992573  1.192241 -1.046780  1.292765


In [ ]:
dd = df[df['W']>0]['Y']
print(dd)

A   -0.376519
B   -0.031160
E   -1.046780
Name: Y, dtype: float64


In [ ]:
#multiple columns
dd = df[df['W']>0][['Y','X']]
print(dd)

          Y         X
A -0.376519  2.084019
B -0.031160  1.035125
E -1.046780  1.192241


In [6]:
import pandas as pd
from numpy.random import randn
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
print(df)
dd2 = df[(df['W']>0) & (df['X']>1)]
print('--------------')
print(dd2)

          W         X         Y         Z
A  2.519054 -1.240028 -0.404527  0.954448
B -0.123600 -0.201074 -0.278543  1.586698
C  0.710596  2.151698  0.613747  0.995240
D  0.362498 -0.980313  0.149425 -0.286368
E  0.909680 -1.081636  0.755827 -0.473256
--------------
          W         X         Y        Z
C  0.710596  2.151698  0.613747  0.99524


In [7]:
#reset the index
view = df.reset_index()
print(view)
df.reset_index(inplace=True)
print(df)

  index         W         X         Y         Z
0     A  2.519054 -1.240028 -0.404527  0.954448
1     B -0.123600 -0.201074 -0.278543  1.586698
2     C  0.710596  2.151698  0.613747  0.995240
3     D  0.362498 -0.980313  0.149425 -0.286368
4     E  0.909680 -1.081636  0.755827 -0.473256
  index         W         X         Y         Z
0     A  2.519054 -1.240028 -0.404527  0.954448
1     B -0.123600 -0.201074 -0.278543  1.586698
2     C  0.710596  2.151698  0.613747  0.995240
3     D  0.362498 -0.980313  0.149425 -0.286368
4     E  0.909680 -1.081636  0.755827 -0.473256


In [ ]:
#reading a file
df = pd.read_csv('data.csv')
print(df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


In [ ]:
#read number of lines
pd.read_csv('data.csv',nrows=5)

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [ ]:
#count number of lines in the file
len(pd.read_csv('data.csv'))

169

In [ ]:
df.head(5)


Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0

In [ ]:
df.tail(5)

Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB
None
